apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379        # Cluster (internal) port
    targetPort: 6379  # Redis listens to request on this port
    nodePort: 32379    # Allow access to service from outside the cluster
    name: redis
  selector:
    app: redis
  type: NodePort